# Generated by Django 4.2.20 on 2025-05-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_masc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_masc', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especie', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Ave', 'Ave'), ('Reptil', 'Reptil'), ('Otro', 'Otro')], max_length=50)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('edad_masc', models.PositiveIntegerField(verbose_name='Edad')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Adoptado', 'Adoptado'), ('En_tratamiento', 'En tratamiento'), ('Reservado', 'Reservado')], default='Disponible', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
